variable "db_identifier" {}
variable "db_engine_version" {}
variable "db_instance_class" {}
variable "db_allocated_storage" {}
variable "db_storage_type" {}
variable "db_multi_az" {}
variable "db_subnet_group_name" {}
variable "db_security_group_ids" {}
variable "db_username" {}
variable "db_password" {}
variable "db_skip_final_snapshot" {}
variable "db_publicly_accessible" {}
variable "db_name" {}
